### ISSUE TITLE
To achieve the effect in the paper, how many epochs we should train the networks？

### ISSUE THREAD

**Issue by cszhilu1998** [gruberto/Gated2Depth#4]
Hi. The default setting in your code is 2 epochs. But how many epochs we should train the networks to achieve the effect in the paper？Thank you.

**Comment by gruberto** [comment]
On the synthetic data set we trained for 20 epochs. Training on real data with sparse lidar ground truth depth is a little bit more tricky since horizontal patterns appear when training too long. Therefore, we have trained on real data only for 2 epochs.
