### ISSUE TITLE
Can not register for the data

### ISSUE THREAD

**Issue by YingkaiFu** [gruberto/Gated2Depth#6]
Hi,
I register the data sever months ago and it has been expired. When I reregister the data, filling all the information I need, and click "Proceed to Data Checking" , the website shows the following message:

Spam recognized: firstname This field must be filled!
Spam recognized: lastname This field must be filled!
Spam recognized: emailfordatadownload This field must be filled!
Spam recognized: marker This field must be filled!
Spam recognized: nameoforganisation This field must be filled!
Spam recognized: street This field must be filled!
Spam recognized: number This field must be filled!
Spam recognized: zipcode This field must be filled!
Spam recognized: city This field must be filled!
Spam recognized: country This field must be filled!
Spam recognized: marker_01 This field must be filled!

I am sure I have filled every thing and ticked all the the box I have to confirm, but it seems I still can't get the download link for my study, can you help to check out the problem?

**Comment by gruberto** [comment]
We are working on resolving this issue. It appears only on the English version of the page. However, as a quick workaround you could use the German page version.

**Comment by YingkaiFu** [comment]
Thanks for your quick reply. Now I get an email containing the download link, but it seems the link has already expired on 5.12. Can you help to update a new link? I can register again using another email.

**Comment by gruberto** [comment]
The registration issue is resolved. We are working on updating the invalid link.

**Comment by gruberto** [comment]
The link in the mail is updated and should work now.
