### ISSUE TITLE
Infer for the video

### ISSUE THREAD

**Issue by jiaqixuac** [gruberto/Gated2Depth#7]
Thanks for the excellent work!

I want to know how to get the depth map for the video, 
e.g., https://github.com/gruberto/Gated2Depth/raw/master/doc/Gated2Depth_real_day.gif

Meanwhile, are the depth maps in the "See Through Fog" obtained using this method?

**Comment by gruberto** [comment]
The depth map in the video is generated by the Gated2Depth model. Unfortunately, the raw images for this video sequence are not part of the published DENSE dataset (https://www.uni-ulm.de/in/iui-drive-u/projekte/dense-datasets/). The given dataset provides only sampled images not sequences.

The paper "Seeing Through Fog Without Seeing Fog: Deep Multimodal Sensor Fusion in Unseen Adverse Weather" deals with multi-sensor fusion based on camera, radar, lidar and gated images. However, there is no explicit depth needed for this approach.
